#############################################################################
# Makefile for building: bin/app.bin
# Generated by qmake (2.01a) (Qt 4.8.7) on: sex mai 12 02:06:05 2017
# Project:  number-recognition.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile number-recognition.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Ibin/.moc -Ibin/.ui
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = bin/.obj/

####### Files

SOURCES       = src/mainwindow.cpp \
		src/main.cpp \
		src/scribblearea.cpp \
		src/perceptron.cpp bin/.moc/moc_scribblearea.cpp \
		bin/.moc/moc_perceptron.cpp
OBJECTS       = bin/.obj/mainwindow.o \
		bin/.obj/main.o \
		bin/.obj/scribblearea.o \
		bin/.obj/perceptron.o \
		bin/.obj/moc_scribblearea.o \
		bin/.obj/moc_perceptron.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		number-recognition.pro
QMAKE_TARGET  = app.bin
DESTDIR       = bin/
TARGET        = bin/app.bin

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): bin/.ui/ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: number-recognition.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile number-recognition.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile number-recognition.pro

dist: 
	@$(CHK_DIR_EXISTS) bin/.obj/app.bin1.0.0 || $(MKDIR) bin/.obj/app.bin1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) bin/.obj/app.bin1.0.0/ && $(COPY_FILE) --parents src/ainwindow.h src/scribblearea.h src/perceptron.h src/ann.h bin/.obj/app.bin1.0.0/ && $(COPY_FILE) --parents src/mainwindow.cpp src/main.cpp src/scribblearea.cpp src/perceptron.cpp bin/.obj/app.bin1.0.0/ && $(COPY_FILE) --parents src/mainwindow.ui bin/.obj/app.bin1.0.0/ && (cd `dirname bin/.obj/app.bin1.0.0` && $(TAR) app.bin1.0.0.tar app.bin1.0.0 && $(COMPRESS) app.bin1.0.0.tar) && $(MOVE) `dirname bin/.obj/app.bin1.0.0`/app.bin1.0.0.tar.gz . && $(DEL_FILE) -r bin/.obj/app.bin1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: bin/.moc/moc_scribblearea.cpp bin/.moc/moc_perceptron.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) bin/.moc/moc_scribblearea.cpp bin/.moc/moc_perceptron.cpp
bin/.moc/moc_scribblearea.cpp: src/scribblearea.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/scribblearea.h -o bin/.moc/moc_scribblearea.cpp

bin/.moc/moc_perceptron.cpp: src/perceptron.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/perceptron.h -o bin/.moc/moc_perceptron.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: bin/.ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) bin/.ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: bin/.ui/ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) bin/.ui/ui_mainwindow.h
bin/.ui/ui_mainwindow.h: src/mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic src/mainwindow.ui -o bin/.ui/ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

bin/.obj/mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/.obj/mainwindow.o src/mainwindow.cpp

bin/.obj/main.o: src/main.cpp src/ann.h \
		src/perceptron.h \
		src/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/.obj/main.o src/main.cpp

bin/.obj/scribblearea.o: src/scribblearea.cpp src/scribblearea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/.obj/scribblearea.o src/scribblearea.cpp

bin/.obj/perceptron.o: src/perceptron.cpp src/perceptron.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/.obj/perceptron.o src/perceptron.cpp

bin/.obj/moc_scribblearea.o: bin/.moc/moc_scribblearea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/.obj/moc_scribblearea.o bin/.moc/moc_scribblearea.cpp

bin/.obj/moc_perceptron.o: bin/.moc/moc_perceptron.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/.obj/moc_perceptron.o bin/.moc/moc_perceptron.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

